FROM alpine

WORKDIR /test

RUN echo "hey" > /etc/foo
RUN echo "baz" > /etc/baz
RUN cp /etc/baz /etc/bar
RUN rm /etc/baz

COPY main.go go.mod ./

WORKDIR /workspace/_static
RUN echo hello > hello.txt
RUN date > index.html
